### ISSUE TITLE
3-button vs full screen gesture navigation bar

### ISSUE THREAD

**Issue by jamesholcomb** [crutchcorn/react-native-immersive-bars#1]
In Android 10, the navigation bar display settings can switch between the old style 3-button layout or full screen gestures (solid bar close to edge bottom).  In my app with the full screen gestures enabled, it works great.  The nav bar is transparent and content renders behind it (my app does not use a bottom toolbar).

I was wondering how to change this behavior when the OS is configured for 3-button layout.  Rather than a transparent nav bar, I would like to set the nav bar to a solid color and increase the inset so that content does not render behind it.

Thanks for developing this package 👍

**Comment by crutchcorn** [comment]
I'm personally not aware of an API that detects when a 3-button layout is used or not (doesn't mean it doesn't exist though, feel free to ping this issue if you're able to find one).

That said! At least with our usage of the package, we fully expected the content to draw under the three-buttons as well. The way we work around content being stuck under the three bars is by using the [`react-native-safe-context`](https://github.com/th3rdwave/react-native-safe-area-context) to add additional bottom padding to items like scroll locations so that we can still draw content under the navbar, but not leave content stuck!

This has worked well on [our app](https://gitshark.dev), as our main testing device is actually set to use three buttons

I hope this helped :)

**Comment by jamesholcomb** [comment]
Thanks for the explanation!  Indeed a safe area could be used.  Though for my personal UX preference, I do not prefer to see scrolled content render behind the 3-button transparent nav bar.  But that's just my opinion :-)  I ended up punting and using `react-native-navigation-bar-color`.

I'll close this and reopen if I see any options materialize.

**Comment by crutchcorn** [comment]
Totally understandable. Glad you found a solution you liked!

**Comment by jamesholcomb** [comment]
Here is what I ended up implementing to detect the navigation mode (verified on a Samsung s10 device).

```java
  @ReactMethod(isBlockingSynchronousMethod = true)
  public int getNavBarInteractionMode() {
      // 0 - 3-button
      // 1 - 2-button
      // 2 - full screen gestures
      Resources resources = reactContext.getResources();
      int resourceId = resources.getIdentifier("config_navBarInteractionMode", "integer", "android");

      if (resourceId > 0) {
         return resources.getInteger(resourceId);
      }

      return 0;
  }
```

https://stackoverflow.com/questions/56689210/how-to-detect-full-screen-gesture-mode-in-android-10
